# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dUid', models.IntegerField(primary_key=True, serialize=False)),
                ('dName', models.CharField(help_text=b'name', max_length=20)),
                ('dPractice', models.CharField(help_text=b'practice', max_length=20)),
            ],
        ),
    ]
