# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171129_0449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
